### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Strannik74** [EranBolan91/Instabot#1]
Good afternoon!
I am very new. Could you add a description of how to install and configure everything

**Comment by EranBolan91** [comment]
First thank you for your email.
Yes I will. I promise to you to do that by the end of the week.

Again, thank you for your email :)

**Comment by EranBolan91** [comment]
> Good afternoon!
> I added description of how to use the program. 
Please if let me know if something isn't working

**Comment by Strannik74** [comment]
> > Добрый день! 
> > Я добавил описание как пользоваться программой. 
> > Пожалуйста, дайте мне знать, если что-то не работает

Good evening
Thanks for the description.
Installed dependencies
Here are the contents of the folder:
❯ ls
bot_folder  chromedriver.exe  insta_bot.ico  __pycache__  users.db  view
bot.py      database          main.py        README.md    utils
❯ python3 main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    window.iconbitmap('insta_bot.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "insta_bot.ico" not defined

What am I doing wrong ..?

**Comment by EranBolan91** [comment]
You did good, for some reason it does not find the image. Try to delete row 8 or just comment " #" and run it again

**Comment by Strannik74** [comment]
I am very new and know little
Thanks you!
Done
from ttkthemes import ThemedTk
from view.layout import Layout
from database import db
"# TODO: use threading timer"
"# TODO: check this https://pypi.org/project/python-crontab/"
"# TODO: how to pass data between classes for the accounts when you add new one. it doesn't update the list"
"# TODO: Settings, need to init when using first time the program with data."
window = ThemedTk(theme='equilux')
#window.iconbitmap('insta_bot.ico')
window.attributes('-fullscreen', True)
data = db.Database()
Layout(window)

window.mainloop()

Next error
python3 main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data = db.Database()
  File "/root/instagram/Instabot/database/db.py", line 34, in __init__
    self.cur.execute(""" CREATE TABLE IF NOT EXISTS unfollow (
sqlite3.OperationalError: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY

**Comment by EranBolan91** [comment]
Found the problem. The problem is "id INT PRIMARY KEY AUTOINCREMENT" - instead INT replace it with INTEGER. It should be like that - "id INTEGER PRIMARY KEY AUTOINCREMENT".
Please let me know if there is another problem

**Comment by Strannik74** [comment]
Thanks
Everything turns out!
It started. He doesn’t want to follow.
![phone2](https://user-images.githubusercontent.com/31668854/83974786-50958f00-a909-11ea-8528-aa18a3475263.jpg)

**Comment by EranBolan91** [comment]
Can you please show me the error log? btw did it follow before?

**Comment by Strannik74** [comment]
Launched for the first time.
On Windows, I'm starting to get as well
-------------------
1591700574465	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.rKwbIM6mMjMl"
1591700580174	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1591700580174	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1591700580175	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1591700580175	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: undefined, line 14: Error: An unexpected error occurred
JavaScript error: moz-extension://18e0ef14-0ce5-418d-85c5-54fd137b2f52/lib/picture_in_picture_overrides.js, line 15: Error: Incorrect argument types for pictureInPictureParent.setOverrides.
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1591700582392	Marionette	INFO	Listening on port 33645
1591700582482	Marionette	WARN	TLS certificate errors will be ignored for this session
1591700621451	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:237:64
[Parent 6548, Gecko_IOThread] WARNING: pipe error (71): Соединение разорвано другой стороной: file /build/firefox-esr-SNKf5O/firefox-esr-68.7.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 6548, Gecko_IOThread] WARNING: pipe error (79): Соединение разорвано другой стороной: file /build/firefox-esr-SNKf5O/firefox-esr-68.7.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 6548, Gecko_IOThread] WARNING: pipe error (123): Соединение разорвано другой стороной: file /build/firefox-esr-SNKf5O/firefox-esr-68.7.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
1591700681745	Marionette	INFO	Stopped listening on port 33645

**Comment by Strannik74** [comment]
On Linux, I use webdriver.Firefox ()
Windows using webdriver.Chrome ('chromedriver.exe')

**Comment by EranBolan91** [comment]
Never got that kind of error. You get it when you try to follow a user? 
Or when you run the program?

**Comment by Strannik74** [comment]
When i run the program

**Comment by Strannik74** [comment]
The program opens the hashtag user and that’s it. Nothing happens next

**Comment by EranBolan91** [comment]
Sorry for the delay, try now to pull. I have added new code.

**Comment by Strannik74** [comment]
Good evening!
I have a mistake again

❯ python3 main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from view.layout import Layout
  File "/root/Instabot/view/layout.py", line 2, in <module>
    from .tab_follow_followers import *
  File "/root/Instabot/view/tab_follow_followers.py", line 5, in <module>
    from utils.schedule import ScheduleCalc
ImportError: cannot import name 'ScheduleCalc' from 'utils.schedule' (/root/Instabot/utils/schedule.py)

**Comment by EranBolan91** [comment]
Its because the path to the file is not correct. 
The file (" schedule.py ") should be placed in " utils " directory. And the " utils " should be inside the main directory

**Comment by Strannik74** [comment]
  ~/Instabot - >master                                       root@kali  ─╮
╰─❯ ls
bot_folder  chromedriver.exe  database  insta_bot.ico  main.py  __pycache__  README.md  utils  view

   ~/Instabot/utils - > master                              root@kali ─╮
╰─❯  ls                                                                                                                                                
schedule.py  utils.py

   ~/Instabot - > master                                     root@kali  ─╮
╰─❯ python3 main.py

 Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from view.layout import Layout
  File "/root/Instabot/view/layout.py", line 2, in <module>
    from .tab_follow_followers import *
  File "/root/Instabot/view/tab_follow_followers.py", line 5, in <module>
    from utils.schedule import ScheduleCalc
ImportError: cannot import name 'ScheduleCalc' from 'utils.schedule' (/root/Instabot/utils/schedule.py)

**Comment by EranBolan91** [comment]
What OS do you have? Linux or Windows?
I'm using Windows and i dont have any problem.
If you are using Linux, i'm not sure but maybe you need to call it in another way?
Eventually it should work, because all the others files you importing them exactly like this class.

**Comment by Strannik74** [comment]
Good afternoon!
Windows 7 is running
The program does not want to follow.

![insta_1](https://user-images.githubusercontent.com/31668854/84985733-bfb78280-b156-11ea-9ce2-e35f3f2b6e2c.jpg)

**Comment by Strannik74** [comment]
I do not understand why the program does not work. May install some component in Windows

**Comment by EranBolan91** [comment]
I know why it doesn't work for you. I see that the language is not english. The bot looking for the word "Follow" , and when its not find it, then nothing happenes.
Several things you can do. The logic happenes in "bot_folder -> main_bot.py "
There is a function called "_follow_user", there is if statement that checks if the button is "Follow", you can change it to your language, or you can change the logic so it click on the button location by xpath
